### PR TITLE
Update rebar.config

### PR DESCRIPTION
**Pull request by redgreat**
change deps git method to https, for docker build needn't set private_key.
thanks.

### CODE REVIEW

**Comment by javiergarea** [comment]
Thank you for your contribution! LGTM 🚀
Nevertheless, the CI pipelines fail so we need some additional changes:
1. We should update both the [`ci.yml`](https://github.com/nomasystems/erf/blob/develop/.github/workflows/ci.yml) and [`docs.yml`](https://github.com/nomasystems/erf/blob/develop/.github/workflows/docs.yml) to remove the `ssh-agent` action.
2. Both the `ndto` and `rebar3_ndto` have its dependencies declared using the `ssh` protocol so they may be also updated to avoid transitive ssh private key dependencies.

I can work on 2., would you mind do 1.? I have no rights on your branch so I cannot update your PR.
@redgreat

**Comment by redgreat** [comment]
> Thank you for your contribution! LGTM 🚀 Nevertheless, the CI pipelines fail so we need some additional changes:
> 
>     1. We should update both the [`ci.yml`](https://github.com/nomasystems/erf/blob/develop/.github/workflows/ci.yml) and [`docs.yml`](https://github.com/nomasystems/erf/blob/develop/.github/workflows/docs.yml) to remove the `ssh-agent` action.
> 
>     2. Both the `ndto` and `rebar3_ndto` have its dependencies declared using the `ssh` protocol so they may be also updated to avoid transitive ssh private key dependencies.
> 
> 
> I can work on 2., would you mind doing 1.? I have no rights on your branch so I cannot update your PR. @redgreat

Thank you very much for reminding me to use the `ssh-agent action` to solve the `private_key` issue. I will use this method to address future GitHub clone permission problems. To avoid more cumbersome authentication, I will modify these two files in the erf repository right away.

**Comment by redgreat** [comment]
I'm sorry, the action still didn't pass. It seems to be caused by the multi-layer dependencies of libraries like ndto that prevented `rebar clean` from succeeding. However, my issue has been resolved, so I'll close this PR.

**Comment by javiergarea** [comment]
It is my fault, I had no time to migrate the protocol for transitive dependencies (i.e., `ndto` and `rebar_ndto`). I'll ping you when I find the time to do it so we can merge this. @redgreat

**Comment by javiergarea** [comment]
fixed in #65

**Pull request closed without merging**
